apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: argocd
spec:
  project: default
  source:
    chart: redpanda
    repoURL: https://charts.redpanda.com
    targetRevision: 5.7.37
    helm:
      releaseName: redpanda
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: redpanda

